[package]
name = "gyazo_slate"
version = "0.1.0"
authors = ["daiiz <da.iz.mg@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
notify = "4.0.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
open="1.2.0"
